### ISSUE TITLE
Serverless Support

### ISSUE THREAD

**Issue by sudo-shubham** [alvarcarto/url-to-pdf-api#20]
Deploy as AWS/Azure Function

**Comment by evaryont** [comment]
There is browserless which seems to have handled a lot of the complicated bits of running Chrome in a serverless fashion already: https://github.com/joelgriffith/browserless

**Comment by kimmobrunfeldt** [comment]
This would be great, but unfortunately I don't have the time to even review this large of a change into the codebase, so I'll have to say this is out of the project's scope. Some thoughts: 

* I would imagine this needing refactoring to have same underlying core functionality, but the bootstrapping would be different in "normal" server and serverless solutions. 
* Serverless solutions are quite different in terms of environments (AWS has API GW, others have something else). Not sure if browserless abstracts this away.
* Increased rendering time due to bootup time
* Are there enough resources for Chrome? Probably yes, but something that came to my mind.

Closing this for now.
