### ISSUE TITLE
how to specific file name?

### ISSUE THREAD

**Issue by postgetme** [alvarcarto/url-to-pdf-api#55]
I noticed the default file name is render.pdf, but how can I specific custom file name?

**Comment by nicky9door** [comment]
I believe 'render.pdf' comes from the browser which uses the last segment of the url (i.e. /api/render/) as the default file name.  You have a few options:

- Change the endpoint in router.js to the desired name
- Use a reverse proxy (Apache, Nginx) to route a path with the desired name to url-to-pdf-api
- Use the `attachmentName` parameter with the desired filename (note: this will set the Content-Disposition header to attachment which means the browser will show a download prompt instead of rendering the pdf in-window)

**Comment by postgetme** [comment]
I tried to use "https://url-to-pdf-api.herokuapp.com/api/render?url=http://google.com&attachmentName=google.pdf", but got {"status":400,"statusText":"Bad Request","errors":[{"field":["attachmentName"],"location":"query","messages":["\"attachmentName\" is not allowed"],"types":["object.allowUnknown"]}]}

**Comment by nicky9door** [comment]
@postgetme The attachment name parameter was added fairly recently (around November) and I don't think the herokuapp has been updated to reflect the change.  You would need to clone the project and run the service on your own machine

**Comment by kimmobrunfeldt** [comment]
The heroku app is updated whenever master is updated unless there's a build error. It works now.
